env:
  global:
    - CC_TEST_REPORTER_ID=cc1fe4a5158d8ce44b44c613458acfbaa97c1240042cecc5e830ce6a09726994

language: php
php:
  - "7.0"
  - "7.1"
  - "7.2"


before_script:
  - composer install --dev --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
  - gpg --with-fingerprint --verify infection.phar.asc infection.phar
  - chmod +x infection.phar


script:
  - mkdir -p build/logs
  - phpunit --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml ./tests
  - ./infection.phar --min-msi=48 --threads=4

after_script:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
